image: python:3.13-alpine

stages:
  - unittests
  - integrationtests

unittests:
  stage: unittests
  before_script:
    - python3 -m pip install --upgrade pip # Link: https://snarky.ca/a-quick-and-dirty-guide-on-how-to-install-packages-for-python/
    - python3 -m pip install -e .
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install -r requirements-dev.txt
    # Sub-section: "Examples:2.3.4". Link: https://pip.pypa.io/en/stable/cli/pip_install/#install-editable
  script:
    - env PYTHONPATH=src python3 -m pytest -vv tests/ # Script taken from picture of CI job log in the assignment

integrationtests:
  stage: integrationtests
  before_script:
    - apk add --no-cache bash
    - apk add --no-cache bats
    # Sub-section: "Adding bash to Alpine Docker image". Link: https://www.cyberciti.biz/faq/alpine-linux-install-bash-using-apk-command/
    - python3 -m pip install --upgrade pip
    - python3 -m pip install .
  script:
    - bats tests/*.bats
